language: python
python: 3.6
sudo: false
env:
  - TOX_ENV=docs
  - TOX_ENV=lint
  - TOX_ENV=py36-django20
  - TOX_ENV=py36-django21
  - TOX_ENV=py36-django22
jobs:
  include:
    - env: TOX_ENV=py37-django21
      python: "3.7"
    - env: TOX_ENV=py37-django22
      python: "3.7"
    - env: TOX_ENV=py38-djangomaster
      python: "3.8"
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
